coverage:
  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
  status:
    project:
      default:
        target: 80%
    patch:
      default:
        target: 80%
